// Font única dels tres directoris d'Actualitat: personalitats, premis i
// esports.
//
// D'aquí en surten tres coses amb `node scripts/directoris/publica.mjs`:
//   1. els fitxers de reserva de la web (src/lib/personalitats.ts, ...),
//   2. les fitxes en Markdown de l'app (infopol-app/src/content/actualitat-*.ts),
//   3. el SQL que substitueix la taula `directories` de Supabase.
// Abans cada lloc tenia la seva còpia i es desquadraven: la web ensenyava
// Starmer i Orbán quan ja no hi eren.
//
// REGLA: només hi entra el que s'ha comprovat en una font actual. Si un
// càrrec no s'ha pogut confirmar, no s'hi posa. Una dada vella en un test
// és pitjor que un buit, perquè algú se l'aprendrà.
//
// `recent: true` marca els canvis dels últims tres mesos.

export const ACTUALITZAT = '2026-09-14';

const E = (flag, position, name, detail, recent) => ({
  flag, position, name, ...(detail ? { detail } : {}), ...(recent ? { recent: true } : {}),
});

/* ═══════════════════════════ PERSONALITATS ═══════════════════════════ */

export const PERSONALITATS = [
  {
    id: 'espanya-govern',
    title: "Govern d'Espanya",
    shortLabel: 'Govern',
    icon: '🇪🇸',
    accent: 'from-red-500 to-amber-600',
    subsections: [
      {
        title: 'Presidència i vicepresidències',
        icon: '🏛️',
        entries: [
          E('🇪🇸', 'President del Govern', 'Pedro Sánchez', 'PSOE · XV legislatura'),
          E('🇪🇸', "Vicepresident primer i ministre d'Economia, Comerç i Empresa", 'Carlos Cuerpo', 'PSOE · vicepresident primer des de la remodelació de març de 2026'),
          E('🇪🇸', 'Vicepresidenta segona i ministra de Treball i Economia Social', 'Yolanda Díaz', 'Sumar'),
          E('🇪🇸', 'Vicepresidenta tercera i ministra per a la Transició Ecològica i el Repte Demogràfic', 'Sara Aagesen', 'PSOE'),
        ],
      },
      {
        title: 'Ministres',
        icon: '💼',
        compact: true,
        entries: [
          E('🇪🇸', 'Afers Exteriors, Unió Europea i Cooperació', 'José Manuel Albares'),
          E('🇪🇸', 'Presidència, Justícia i Relacions amb les Corts', 'Félix Bolaños'),
          E('🇪🇸', 'Defensa', 'Margarita Robles'),
          E('🇪🇸', 'Hisenda', 'Arcadi España', 'Des de març de 2026; substitueix María Jesús Montero'),
          E('🇪🇸', 'Interior', 'Fernando Grande-Marlaska'),
          E('🇪🇸', 'Transports i Mobilitat Sostenible', 'Óscar Puente'),
          E('🇪🇸', 'Educació, Formació Professional i Esports', 'Milagros Tolón', 'Substitueix Pilar Alegría'),
          E('🇪🇸', 'Indústria i Turisme', 'Jordi Hereu'),
          E('🇪🇸', 'Agricultura, Pesca i Alimentació', 'Luis Planas'),
          E('🇪🇸', 'Política Territorial i Memòria Democràtica', 'Ángel Víctor Torres'),
          E('🇪🇸', 'Habitatge i Agenda Urbana', 'Isabel Rodríguez'),
          E('🇪🇸', 'Cultura', 'Ernest Urtasun', 'Sumar'),
          E('🇪🇸', 'Sanitat', 'Mónica García', 'Sumar'),
          E('🇪🇸', 'Drets Socials, Consum i Agenda 2030', 'Pablo Bustinduy', 'Sumar'),
          E('🇪🇸', 'Ciència, Innovació i Universitats', 'Diana Morant'),
          E('🇪🇸', 'Igualtat', 'Ana Redondo'),
          E('🇪🇸', 'Inclusió, Seguretat Social i Migracions', 'Elma Saiz'),
          E('🇪🇸', 'Transformació Digital i de la Funció Pública', 'Óscar López'),
          E('🇪🇸', 'Joventut i Infància', 'Sira Rego', 'Sumar'),
        ],
      },
    ],
  },
  {
    id: 'espanya-estat',
    title: 'Estat: Corona, Corts i alts òrgans',
    shortLabel: 'Estat',
    icon: '👑',
    accent: 'from-amber-500 to-orange-700',
    subsections: [
      {
        title: 'Corona',
        icon: '👑',
        entries: [
          E('👑', "Rei d'Espanya", 'Felip VI'),
          E('👑', 'Reina', 'Letícia'),
          E('👑', "Princesa d'Astúries", 'Elionor de Borbó', 'Hereva de la Corona'),
          E('👑', 'Cap de la Casa de S. M. el Rei', 'Camilo Villarino'),
        ],
      },
      {
        title: 'Corts Generals i partits',
        icon: '🗳️',
        entries: [
          E('🏛️', 'Presidenta del Congrés dels Diputats', 'Francina Armengol', 'PSOE'),
          E('🏛️', 'President del Senat', 'Pedro Rollán', 'PP'),
          E('🔵', "PP · líder de l'oposició", 'Alberto Núñez Feijóo'),
          E('🟢', 'Vox · president', 'Santiago Abascal'),
          E('🟣', 'Podem · secretària general', 'Ione Belarra'),
          E('🟡', 'ERC · president', 'Oriol Junqueras'),
          E('🟠', 'Junts · president', 'Carles Puigdemont'),
          E('🟩', 'PNB · president de l\'Euzkadi Buru Batzar', 'Aitor Esteban'),
          E('🟩', 'EH Bildu · coordinador general', 'Arnaldo Otegi'),
        ],
      },
      {
        title: 'Justícia i òrgans de l\'Estat',
        icon: '⚖️',
        entries: [
          E('⚖️', 'President del Tribunal Constitucional', 'Cándido Conde-Pumpido'),
          E('⚖️', 'Presidenta del Tribunal Suprem i del CGPJ', 'Isabel Perelló', 'Primera dona al càrrec'),
          E('⚖️', "Fiscal General de l'Estat", 'Teresa Peramato', "Des de desembre de 2025; substitueix Álvaro García Ortiz, condemnat pel Tribunal Suprem"),
          E('⚖️', "President de l'Audiència Nacional", 'Juan Manuel Fernández'),
          E('📊', 'Presidenta del Tribunal de Comptes', 'Enriqueta Chicano'),
          E('📜', "Presidenta del Consell d'Estat", 'Carmen Calvo'),
          E('🛡️', 'Defensor del Poble', 'Ángel Gabilondo'),
          E('💶', "Governador del Banc d'Espanya", 'José Luis Escrivá'),
        ],
      },
      {
        title: 'Seguretat i defensa',
        icon: '🚓',
        entries: [
          E('👮', 'Director General de la Policia Nacional', 'Francisco Pardo Piqueras'),
          E('🚓', 'Directora General de la Guàrdia Civil', 'Mercedes González'),
          E('🕵️', 'Directora del CNI', 'Esperanza Casteleiro'),
          E('🎖️', "Cap d'Estat Major de la Defensa (JEMAD)", 'Teodoro E. López Calderón', 'Almirall general'),
          E('🇪🇸', 'Delegat del Govern a Catalunya', 'Carlos Prieto'),
        ],
      },
    ],
  },
  {
    id: 'espanya-comunitats',
    title: 'Presidents autonòmics',
    shortLabel: 'Comunitats',
    icon: '🗺️',
    accent: 'from-emerald-500 to-teal-700',
    subsections: [
      {
        title: 'Les 17 comunitats i les 2 ciutats autònomes',
        icon: '🗺️',
        entries: [
          E('🟩', 'Andalusia', 'Juanma Moreno', 'PP · guanya les eleccions del 17 de maig de 2026, però perd la majoria absoluta (53 escons)'),
          E('🟨', 'Aragó', 'Jorge Azcón', 'PP · eleccions anticipades el 8 de febrer de 2026'),
          E('🟦', 'Astúries', 'Adrián Barbón', 'PSOE'),
          E('🟪', 'Illes Balears', 'Marga Prohens', 'PP'),
          E('🟨', 'Canàries', 'Fernando Clavijo', 'Coalició Canària'),
          E('🟩', 'Cantàbria', 'María José Sáenz de Buruaga', 'PP'),
          E('🟫', 'Castella-la Manxa', 'Emiliano García-Page', 'PSOE'),
          E('🟪', 'Castella i Lleó', 'Alfonso Fernández Mañueco', 'PP · guanya les eleccions del 15 de març de 2026 sense majoria absoluta'),
          E('🟥', 'Catalunya', 'Salvador Illa', "PSC · 133è president de la Generalitat, des d'agost de 2024"),
          E('🟥', 'Comunitat de Madrid', 'Isabel Díaz Ayuso', 'PP'),
          E('🟧', 'Comunitat Valenciana', 'Juanfran Pérez Llorca', 'PP · des de desembre de 2025; substitueix Carlos Mazón, que va dimitir per la gestió de la DANA'),
          E('🟩', 'Extremadura', 'María Guardiola', 'PP · reelegida després de les eleccions anticipades de desembre de 2025'),
          E('🟦', 'Galícia', 'Alfonso Rueda', 'PP'),
          E('🟥', 'La Rioja', 'Gonzalo Capellán', 'PP'),
          E('🟥', 'Navarra', 'María Chivite', 'PSN-PSOE'),
          E('🟩', 'País Basc', 'Imanol Pradales', "PNB · lehendakari des de juny de 2024"),
          E('🟧', 'Regió de Múrcia', 'Fernando López Miras', 'PP'),
          E('🏙️', 'Ceuta (ciutat autònoma)', 'Juan Jesús Vivas', 'PP'),
          E('🏙️', 'Melilla (ciutat autònoma)', 'Juan José Imbroda', 'PP'),
        ],
      },
    ],
  },
  {
    id: 'espanya-alcaldes',
    title: 'Alcaldes de les grans ciutats',
    shortLabel: 'Alcaldes',
    icon: '🏙️',
    accent: 'from-sky-500 to-blue-700',
    subsections: [
      {
        title: 'Les ciutats més poblades',
        icon: '🏙️',
        compact: true,
        entries: [
          E('🏙️', 'Madrid', 'José Luis Martínez-Almeida', 'PP'),
          E('🏙️', 'Barcelona', 'Jaume Collboni', 'PSC'),
          E('🏙️', 'València', 'María José Catalá', 'PP'),
          E('🏙️', 'Saragossa', 'Natalia Chueca', 'PP'),
          E('🏙️', 'Sevilla', 'José Luis Sanz', 'PP'),
          E('🏙️', 'Màlaga', 'Francisco de la Torre', 'PP · alcalde des del 2000'),
          E('🏙️', 'Múrcia', 'Rebeca Pérez', 'PP · des del 22 de maig de 2026, després de la mort de José Ballesta', true),
          E('🏙️', 'Palma', 'Jaime Martínez', 'PP'),
          E('🏙️', 'Las Palmas de Gran Canaria', 'Carolina Darias', 'PSOE'),
          E('🏙️', 'Alacant', 'Luis Barcala', 'PP'),
          E('🏙️', 'Bilbao', 'Juan Mari Aburto', 'PNB'),
          E('🏙️', 'Còrdova', 'José María Bellido', 'PP'),
          E('🏙️', 'Valladolid', 'Jesús Julio Carnero', 'PP'),
          E('🏙️', 'Vigo', 'Abel Caballero', 'PSdeG-PSOE'),
          E('🏙️', "L'Hospitalet de Llobregat", 'David Quirós', 'PSC · des de juny de 2024'),
          E('🏙️', 'Gijón', 'Carmen Moriyón', 'Foro Asturias'),
          E('🏙️', 'Vitòria', 'Maider Etxebarria', 'PSE-EE'),
          E('🏙️', 'A Corunya', 'Inés Rey', 'PSdeG-PSOE'),
          E('🏙️', 'Elx', 'Pablo Ruz', 'PP'),
          E('🏙️', 'Granada', 'Marifrán Carazo', 'PP'),
          E('🏙️', 'Terrassa', 'Jordi Ballart', 'Tot per Terrassa'),
          E('🏙️', 'Badalona', 'Xavier García Albiol', 'PP'),
          E('🏙️', 'Sabadell', 'Marta Farrés', 'PSC'),
          E('🏙️', 'Oviedo', 'Alfredo Canteli', 'PP'),
          E('🏙️', 'Pamplona', 'Joseba Asiron', 'EH Bildu · des de desembre de 2023'),
          E('🏙️', 'Sant Sebastià', 'Jon Insausti', "PNB · des d'octubre de 2025"),
        ],
      },
      {
        title: 'Altres capitals de província',
        icon: '📍',
        compact: true,
        entries: [
          E('📍', 'Almeria', 'María del Mar Vázquez', 'PP'),
          E('📍', 'Cadis', 'Bruno García', 'PP'),
          E('📍', 'Huelva', 'Pilar Miranda', 'PP'),
          E('📍', 'Jaén', 'Julio Millán', 'PSOE · des de gener de 2025, per moció de censura'),
          E('📍', 'Castelló de la Plana', 'Begoña Carrasco', 'PP'),
          E('📍', 'Santander', 'Gema Igual', 'PP'),
          E('📍', 'Logronyo', 'Conrado Escobar', 'PP'),
          E('📍', 'Burgos', 'Cristina Ayala', 'PP'),
          E('📍', 'Salamanca', 'Carlos García Carbayo', 'PP'),
          E('📍', 'Lleó', 'José Antonio Diez', 'PSOE'),
          E('📍', 'Palència', 'Miriam Andrés', 'PSOE'),
          E('📍', 'Sòria', 'Javier Antón', "PSOE · des de l'abril de 2026"),
          E('📍', 'Segòvia', 'José Mazarías', 'PP'),
          E('📍', 'Toledo', 'Carlos Velázquez', 'PP'),
          E('📍', 'Ciudad Real', 'Francisco Cañizares', 'PP'),
          E('📍', 'Guadalajara', 'Ana Guarinos', 'PP'),
          E('📍', 'Albacete', 'Manuel Serrano', 'PP'),
          E('📍', 'Badajoz', 'Ignacio Gragera', 'PP'),
          E('📍', 'Càceres', 'Rafael Mateos', 'PP'),
          E('📍', 'Osca', 'Lorena Orduna', 'PP'),
          E('📍', 'Terol', 'Emma Buj', 'PP'),
          E('📍', 'Santiago de Compostel·la', 'Goretti Sanmartín', 'BNG'),
          E('📍', 'Lugo', 'Elena Candia', 'PP · des de maig de 2026, per moció de censura'),
          E('📍', 'Ourense', 'Gonzalo Pérez Jácome', 'Democracia Ourensana'),
          E('📍', 'Pontevedra', 'Miguel Anxo Fernández Lores', 'BNG · alcalde des de 1999'),
          E('📍', 'Santa Cruz de Tenerife', 'José Manuel Bermúdez', 'Coalició Canària'),
          E('📍', 'Girona', 'Lluc Salellas', 'Guanyem Girona'),
          E('📍', 'Lleida', 'Fèlix Larrosa', 'PSC'),
          E('📍', 'Tarragona', 'Rubén Viñuales', 'PSC'),
        ],
      },
      {
        title: 'Àrea de Barcelona i Baix Llobregat',
        icon: '🌊',
        compact: true,
        entries: [
          E('🌊', 'Mataró', 'David Bote', 'PSC'),
          E('🌊', 'Reus', 'Sandra Guaita', 'PSC · primera alcaldessa de la ciutat'),
          E('🌊', 'Sant Cugat del Vallès', 'Josep Maria Vallès', 'Junts'),
          E('🌊', 'Santa Coloma de Gramenet', 'Mireia González', "PSC · des d'agost de 2024, quan Núria Parlon va passar a consellera"),
          E('🌊', 'Cornellà de Llobregat', 'Antonio Balmón', 'PSC · alcalde des de 2004'),
          E('🌊', 'Sant Boi de Llobregat', 'Lluïsa Moret', 'PSC · també presidenta de la Diputació de Barcelona'),
          E('🌊', 'Castelldefels', 'Manuel Reyes', 'PP'),
          E('🌊', 'Gavà', 'Gemma Badia', 'PSC'),
          E('🌊', 'El Prat de Llobregat', 'Alba Bou', 'Comuns · des de gener de 2025'),
          E('🌊', 'Viladecans', 'Olga Morales', "PSC · des d'octubre de 2024; primera alcaldessa de la ciutat"),
        ],
      },
    ],
  },
  {
    id: 'catalunya',
    title: 'Catalunya',
    shortLabel: 'Catalunya',
    icon: '🏛️',
    accent: 'from-yellow-500 to-red-600',
    subsections: [
      {
        title: 'Govern de la Generalitat',
        icon: '🏛️',
        entries: [
          E('🟥', 'President de la Generalitat', 'Salvador Illa', "PSC · 133è president, des d'agost de 2024"),
          E('🟥', 'Conseller de la Presidència', 'Albert Dalmau'),
          E('🟥', "Consellera d'Economia i Finances", 'Alícia Romero'),
          E('🟥', "Consellera d'Interior i Seguretat Pública", 'Núria Parlon', 'Abans, alcaldessa de Santa Coloma de Gramenet'),
          E('🟥', 'Conseller de Justícia i Qualitat Democràtica', 'Ramon Espadaler'),
          E('🟥', 'Consellera de Territori, Habitatge i Transició Ecològica', 'Sílvia Paneque', 'També portaveu del Govern'),
          E('🟥', 'Consellera de Salut', 'Olga Pané'),
          E('🟥', "Consellera d'Educació i Formació Professional", 'Esther Niubó'),
          E('🟥', 'Conseller de Drets Socials i Inclusió', 'Raúl Moreno', 'Substitueix Mònica Martínez Bravo'),
          E('🟥', "Conseller d'Empresa i Treball", 'Miquel Sàmper'),
          E('🟥', "Consellera d'Igualtat i Feminismes", 'Eva Menor'),
          E('🟥', "Conseller d'Unió Europea i Acció Exterior", 'Jaume Duch'),
          E('🟥', 'Consellera de Recerca i Universitats', 'Núria Montserrat'),
          E('🟥', "Conseller d'Agricultura, Ramaderia, Pesca i Alimentació", 'Òscar Ordeig'),
          E('🟥', "Conseller d'Esports", 'Berni Álvarez'),
          E('🟥', 'Consellera de Cultura', 'Sònia Hernández'),
          E('🟥', 'Conseller de Política Lingüística', 'Francesc Xavier Vila'),
        ],
      },
      {
        title: 'Seguretat',
        icon: '👮',
        entries: [
          E('👮', 'Director General de la Policia', 'Josep Lluís Trapero'),
          E('👮', "Comissària en cap dels Mossos d'Esquadra", 'Sílvia Catà', 'Pren possessió el 15 de setembre de 2026; primera dona al capdavant del cos; substitueix Miquel Esquius, que es jubila', true),
        ],
      },
      {
        title: 'Parlament i institucions',
        icon: '⚖️',
        entries: [
          E('🏛️', 'President del Parlament de Catalunya', 'Josep Rull', 'Junts · des de juny de 2024'),
          E('🛡️', 'Síndica de Greuges de Catalunya', 'Esther Giménez-Salinas'),
          E('⚖️', 'Presidenta del Tribunal Superior de Justícia de Catalunya', 'Mercè Caso', "Des d'abril de 2025"),
          E('⚖️', 'Fiscal superior de Catalunya', 'Francisco Bañeres'),
          E('🇪🇸', 'Delegat del Govern espanyol a Catalunya', 'Carlos Prieto'),
          E('🏛️', 'Presidenta de la Diputació de Barcelona', 'Lluïsa Moret', 'PSC · alcaldessa de Sant Boi'),
        ],
      },
      {
        title: 'Partits i entitats',
        icon: '🗳️',
        entries: [
          E('🔴', 'PSC · primer secretari', 'Salvador Illa'),
          E('🟠', 'Junts · president', 'Carles Puigdemont'),
          E('🟡', 'ERC · president', 'Oriol Junqueras'),
          E('🔵', 'PP català · president', 'Alejandro Fernández'),
          E('🟢', 'Vox Catalunya · líder', 'Ignacio Garriga'),
          E('⚫', 'Aliança Catalana · líder', 'Sílvia Orriols'),
          E('🎗️', "President d'Òmnium Cultural", 'Xavier Antich'),
          E('🎗️', "President de l'Assemblea Nacional Catalana", 'Lluís Llach'),
        ],
      },
    ],
  },
  {
    id: 'unio-europea',
    title: 'Unió Europea',
    shortLabel: 'UE',
    icon: '🇪🇺',
    accent: 'from-blue-500 to-indigo-700',
    subsections: [
      {
        title: 'Institucions de la UE',
        icon: '🇪🇺',
        entries: [
          E('🇪🇺', 'Presidenta de la Comissió Europea', 'Ursula von der Leyen', 'Segon mandat, des de desembre de 2024'),
          E('🇪🇺', 'President del Consell Europeu', 'António Costa', 'Des de desembre de 2024'),
          E('🇪🇺', 'Presidenta del Parlament Europeu', 'Roberta Metsola', 'Mandat fins al gener de 2027'),
          E('🇪🇺', 'Alta Representant per a Afers Exteriors', 'Kaja Kallas', 'També vicepresidenta de la Comissió'),
          E('💶', 'Presidenta del Banc Central Europeu', 'Christine Lagarde'),
          E('💶', "President de l'Eurogrup", 'Kyriakos Pierrakakis', 'Grècia · des de gener de 2026'),
          E('⚖️', 'President del Tribunal de Justícia de la UE', 'Koen Lenaerts'),
          E('💶', "Presidenta del Banc Europeu d'Inversions", 'Nadia Calviño'),
          E('🛡️', 'Defensora del Poble Europeu', 'Teresa Anjinho'),
          E('🇮🇪', 'Presidència del Consell de la UE', 'Irlanda', 'Juliol-desembre de 2026; després, Lituània (gener-juny de 2027)'),
          E('👮', "Director executiu d'Europol (en funcions)", 'Jürgen Ebner', 'Des de maig de 2026, quan Catherine De Bolle va plegar'),
        ],
      },
    ],
  },
  {
    id: 'organismes',
    title: 'Organismes internacionals',
    shortLabel: 'Organismes',
    icon: '🌐',
    accent: 'from-cyan-500 to-sky-700',
    subsections: [
      {
        title: 'ONU i agències',
        icon: '🇺🇳',
        entries: [
          E('🇺🇳', "Secretari general de l'ONU", 'António Guterres', "Mandat fins al 31 de desembre de 2026. El Consell de Seguretat tria el successor; als sondejos lideren Carolyn Rodrigues Birkett, Rebeca Grynspan i Rafael Grossi"),
          E('🇺🇳', "President de l'Assemblea General de l'ONU", 'Khalilur Rahman', 'Bangladesh · 81a sessió, des del 8 de setembre de 2026', true),
          E('🩺', "Director general de l'OMS", 'Tedros Adhanom Ghebreyesus'),
          E('🎓', 'Director general de la UNESCO', 'Khaled El-Enany', "Egipte · des de novembre de 2025; primer director general d'un país àrab"),
          E('🏕️', "Alt Comissionat de l'ONU per als Refugiats (ACNUR)", 'Barham Salih', "Expresident d'Iraq · des de gener de 2026"),
          E('⚛️', "Director general de l'OIEA", 'Rafael Grossi'),
          E('🕊️', "Alt Comissionat de l'ONU per als Drets Humans", 'Volker Türk'),
          E('🧒', "Directora executiva d'UNICEF", 'Catherine Russell'),
        ],
      },
      {
        title: 'Seguretat, justícia i economia',
        icon: '🛡️',
        entries: [
          E('🛡️', "Secretari general de l'OTAN", 'Mark Rutte', "Des d'octubre de 2024; abans, primer ministre dels Països Baixos"),
          E('🚓', "Secretari general d'Interpol", 'Valdecy Urquiza', 'Brasil'),
          E('⚖️', 'Presidenta de la Cort Penal Internacional', 'Tomoko Akane'),
          E('⚖️', 'President del Tribunal Europeu de Drets Humans', 'Mattias Guyomar', 'França · des de maig de 2025'),
          E('🏛️', "Secretari general del Consell d'Europa", 'Alain Berset'),
          E('🕊️', "Secretari general de l'OSCE", 'Feridun Sinirlioğlu'),
          E('💵', 'Directora gerent del FMI', 'Kristalina Georgieva'),
          E('💵', 'President del Banc Mundial', 'Ajay Banga'),
          E('📦', "Directora general de l'OMC", 'Ngozi Okonjo-Iweala'),
          E('📈', "Secretari general de l'OCDE", 'Mathias Cormann'),
          E('🏅', 'Presidenta del Comitè Olímpic Internacional', 'Kirsty Coventry', 'Primera dona al càrrec · des de juny de 2025'),
        ],
      },
    ],
  },
  {
    id: 'europa',
    title: "Europa: caps d'Estat i de govern",
    shortLabel: 'Europa',
    icon: '🏰',
    accent: 'from-indigo-500 to-violet-700',
    subsections: [
      {
        title: 'Els 27 de la Unió Europea',
        icon: '🇪🇺',
        compact: true,
        entries: [
          E('🇩🇪', 'Alemanya', 'Friedrich Merz', "Canceller · president: Frank-Walter Steinmeier"),
          E('🇦🇹', 'Àustria', 'Christian Stocker', 'Canceller · president: Alexander Van der Bellen'),
          E('🇧🇪', 'Bèlgica', 'Bart De Wever', 'Primer ministre · rei: Felip (Philippe)'),
          E('🇧🇬', 'Bulgària', 'Rumen Radev', "Primer ministre des de maig de 2026 (abans havia estat president) · presidenta: Iliana Iotova, la primera dona"),
          E('🇨🇾', 'Xipre', 'Nikos Christodoulides', 'President (sistema presidencial)'),
          E('🇭🇷', 'Croàcia', 'Andrej Plenković', 'Primer ministre · president: Zoran Milanović'),
          E('🇩🇰', 'Dinamarca', 'Mette Frederiksen', 'Primera ministra, tercer mandat després de les eleccions de març de 2026 · rei: Frederic X'),
          E('🇸🇰', 'Eslovàquia', 'Robert Fico', 'Primer ministre · president: Peter Pellegrini'),
          E('🇸🇮', 'Eslovènia', 'Janez Janša', 'Primer ministre per quarta vegada, des de juny de 2026 · presidenta: Nataša Pirc Musar', true),
          E('🇪🇸', 'Espanya', 'Pedro Sánchez', 'President del Govern · rei: Felip VI'),
          E('🇪🇪', 'Estònia', 'Kristen Michal', "Primer ministre · president: Alar Karis; Ülle Madise, elegida el 2 de setembre, pren possessió el 12 d'octubre de 2026", true),
          E('🇫🇮', 'Finlàndia', 'Petteri Orpo', 'Primer ministre · president: Alexander Stubb'),
          E('🇫🇷', 'França', 'Emmanuel Macron', 'President · primer ministre: Sébastien Lecornu'),
          E('🇬🇷', 'Grècia', 'Kyriakos Mitsotakis', 'Primer ministre · president: Konstantinos Tasoulas'),
          E('🇭🇺', 'Hongria', 'Péter Magyar', "Primer ministre des del 9 de maig de 2026; posa fi a 16 anys d'Orbán · president: András Baka, des d'agost de 2026", true),
          E('🇮🇪', 'Irlanda', 'Micheál Martin', 'Taoiseach · presidenta: Catherine Connolly'),
          E('🇮🇹', 'Itàlia', 'Giorgia Meloni', 'Primera ministra · president: Sergio Mattarella'),
          E('🇱🇻', 'Letònia', 'Andris Kulbergs', 'Primer ministre des del 28 de maig de 2026 · president: Edgars Rinkēvičs'),
          E('🇱🇹', 'Lituània', 'Mindaugas Sinkevičius', 'Primer ministre des de juliol de 2026 · president: Gitanas Nausėda', true),
          E('🇱🇺', 'Luxemburg', 'Luc Frieden', 'Primer ministre · gran duc: Guillem V'),
          E('🇲🇹', 'Malta', 'Robert Abela', 'Primer ministre · presidenta: Myriam Spiteri Debono'),
          E('🇳🇱', 'Països Baixos', 'Rob Jetten', 'Primer ministre des del 23 de febrer de 2026, el més jove de la història del país · rei: Guillem Alexandre'),
          E('🇵🇱', 'Polònia', 'Donald Tusk', 'Primer ministre · president: Karol Nawrocki'),
          E('🇵🇹', 'Portugal', 'Luís Montenegro', 'Primer ministre · president: António José Seguro, des del 9 de març de 2026'),
          E('🇷🇴', 'Romania', 'Ilie Bolojan', 'Primer ministre en funcions: el seu govern va caure el maig de 2026 i el Parlament ha rebutjat els candidats alternatius · president: Nicușor Dan'),
          E('🇸🇪', 'Suècia', 'Ulf Kristersson', 'Primer ministre · eleccions del 13 de setembre de 2026 amb un resultat molt ajustat · rei: Carles XVI Gustau', true),
          E('🇨🇿', 'Txèquia', 'Andrej Babiš', 'Primer ministre des de desembre de 2025 · president: Petr Pavel'),
        ],
      },
      {
        title: "Resta d'Europa",
        icon: '🗺️',
        compact: true,
        entries: [
          E('🇬🇧', 'Regne Unit', 'Andy Burnham', 'Primer ministre des del 20 de juliol de 2026; substitueix Keir Starmer · rei: Carles III', true),
          E('🇳🇴', 'Noruega', 'Jonas Gahr Støre', "Primer ministre · rei: Haakon VIII, des del 28 d'agost de 2026 per la mort de Harald V", true),
          E('🇨🇭', 'Suïssa', 'Guy Parmelin', 'President de la Confederació el 2026 (el càrrec és rotatori i anual)'),
          E('🇮🇸', 'Islàndia', 'Kristrún Frostadóttir', 'Primera ministra · presidenta: Halla Tómasdóttir'),
          E('🇦🇩', 'Andorra', 'Xavier Espot', "Cap de Govern · coprínceps: Emmanuel Macron i el bisbe d'Urgell, Josep-Lluís Serrano Pentinat"),
          E('🇲🇨', 'Mònaco', 'Albert II', "Príncep sobirà · ministre d'Estat: Christophe Mirmand"),
          E('🇱🇮', 'Liechtenstein', 'Brigitte Haas', 'Primera ministra · príncep: Joan Adam II'),
          E('🇸🇲', 'San Marino', 'Alice Mina i Vladimiro Selva', 'Capitans regents (canvien cada sis mesos)'),
          E('🇺🇦', 'Ucraïna', 'Volodímir Zelenski', 'President · primer ministre: Serhí Koretski, des del 16 de juliol de 2026', true),
          E('🇷🇺', 'Rússia', 'Vladímir Putin', 'President · primer ministre: Mikhaïl Mixustin'),
          E('🇧🇾', 'Bielorússia', 'Aleksandr Lukaixenko', 'President · primer ministre: Aleksandr Turtxin'),
          E('🇹🇷', 'Turquia', 'Recep Tayyip Erdoğan', 'President'),
          E('🇷🇸', 'Sèrbia', 'Aleksandar Vučić', "President · primer ministre: Đuro Macut · eleccions anticipades el 25 d'octubre de 2026"),
          E('🇲🇩', 'Moldàvia', 'Maia Sandu', 'Presidenta · primer ministre: Vasile Tofan, des de juliol de 2026', true),
          E('🇲🇰', 'Macedònia del Nord', 'Hristijan Mickoski', 'Primer ministre · presidenta: Gordana Siljanovska-Davkova'),
          E('🇦🇱', 'Albània', 'Edi Rama', 'Primer ministre · president: Bajram Begaj'),
          E('🇲🇪', 'Montenegro', 'Milojko Spajić', 'Primer ministre · president: Jakov Milatović'),
          E('🇧🇦', 'Bòsnia i Hercegovina', 'Borjana Krišto', 'Presidenta del Consell de Ministres · presidència col·legiada de tres membres'),
          E('🇽🇰', 'Kosovo', 'Albin Kurti', "Primer ministre · presidenta en funcions: Albulena Haxhiu, des d'abril de 2026"),
          E('🇬🇪', 'Geòrgia', 'Irakli Kobakhidze', 'Primer ministre · president: Mikheil Kavelashvili'),
          E('🇦🇲', 'Armènia', 'Nikol Pashinyan', 'Primer ministre · el seu partit guanya les eleccions de juny de 2026'),
          E('🇦🇿', 'Azerbaidjan', 'Ilham Aliyev', 'President'),
        ],
      },
    ],
  },
  {
    id: 'america',
    title: 'Amèrica',
    shortLabel: 'Amèrica',
    icon: '🌎',
    accent: 'from-orange-500 to-rose-700',
    subsections: [
      {
        title: 'Estats Units',
        icon: '🇺🇸',
        entries: [
          E('🇺🇸', 'President dels Estats Units', 'Donald Trump', '47è president · des del 20 de gener de 2025'),
          E('🇺🇸', 'Vicepresident', 'JD Vance'),
          E('🇺🇸', "Secretari d'Estat", 'Marco Rubio'),
          E('🇺🇸', 'Secretari de Guerra (Defensa)', 'Pete Hegseth'),
          E('🇺🇸', 'Secretari del Tresor', 'Scott Bessent'),
          E('🇺🇸', 'Fiscal general', 'Todd Blanche', "Des d'abril de 2026; substitueix Pam Bondi"),
          E('🇺🇸', 'Secretari de Seguretat Nacional', 'Markwayne Mullin', 'Des de març de 2026; substitueix Kristi Noem'),
          E('🇺🇸', 'Secretari de Salut', 'Robert F. Kennedy Jr.', 'Nebot del president John F. Kennedy'),
          E('🇺🇸', 'Director del FBI', 'Kash Patel'),
          E('🇺🇸', 'President de la Reserva Federal', 'Kevin Warsh', 'Des del 22 de maig de 2026; substitueix Jerome Powell'),
          E('🇺🇸', 'President de la Cambra de Representants', 'Mike Johnson'),
          E('🇺🇸', 'President del Tribunal Suprem', 'John Roberts'),
        ],
      },
      {
        title: 'Nord i Centreamèrica i Carib',
        icon: '🌴',
        compact: true,
        entries: [
          E('🇨🇦', 'Canadà', 'Mark Carney', 'Primer ministre · rei: Carles III'),
          E('🇲🇽', 'Mèxic', 'Claudia Sheinbaum', "Presidenta, la primera dona · des d'octubre de 2024"),
          E('🇬🇹', 'Guatemala', 'Bernardo Arévalo', 'President'),
          E('🇸🇻', 'El Salvador', 'Nayib Bukele', 'President'),
          E('🇭🇳', 'Hondures', 'Nasry Asfura', 'President'),
          E('🇳🇮', 'Nicaragua', 'Daniel Ortega i Rosario Murillo', 'Copresidents'),
          E('🇨🇷', 'Costa Rica', 'Laura Fernández', 'Presidenta'),
          E('🇵🇦', 'Panamà', 'José Raúl Mulino', 'President'),
          E('🇨🇺', 'Cuba', 'Miguel Díaz-Canel', 'President · primer ministre: Manuel Marrero'),
          E('🇩🇴', 'República Dominicana', 'Luis Abinader', 'President'),
          E('🇭🇹', 'Haití', 'Alix Didier Fils-Aimé', 'Primer ministre · presidència vacant'),
        ],
      },
      {
        title: 'Sud-amèrica',
        icon: '🌎',
        compact: true,
        entries: [
          E('🇦🇷', 'Argentina', 'Javier Milei', 'President'),
          E('🇧🇴', 'Bolívia', 'Rodrigo Paz', 'President'),
          E('🇧🇷', 'Brasil', 'Luiz Inácio Lula da Silva', "President · eleccions presidencials el 4 d'octubre de 2026"),
          E('🇨🇱', 'Xile', 'José Antonio Kast', 'President des de març de 2026'),
          E('🇨🇴', 'Colòmbia', 'Abelardo de la Espriella', "President des del 7 d'agost de 2026; guanya Iván Cepeda a la segona volta", true),
          E('🇪🇨', 'Equador', 'Daniel Noboa', 'President'),
          E('🇵🇾', 'Paraguai', 'Santiago Peña', 'President'),
          E('🇵🇪', 'Perú', 'Keiko Fujimori', 'Presidenta des del 28 de juliol de 2026; la primera dona elegida a les urnes', true),
          E('🇺🇾', 'Uruguai', 'Yamandú Orsi', 'President'),
          E('🇻🇪', 'Veneçuela', 'Delcy Rodríguez', 'Presidenta encarregada des del 5 de gener de 2026, després que els EUA capturessin Nicolás Maduro'),
          E('🇬🇾', 'Guyana', 'Irfaan Ali', 'President'),
        ],
      },
    ],
  },
  {
    id: 'asia-africa',
    title: 'Àsia, Orient Mitjà i Àfrica',
    shortLabel: 'Àsia i Àfrica',
    icon: '🌏',
    accent: 'from-rose-500 to-fuchsia-700',
    subsections: [
      {
        title: 'Àsia i Pacífic',
        icon: '🌏',
        compact: true,
        entries: [
          E('🇨🇳', 'Xina', 'Xi Jinping', 'President i secretari general del Partit · primer ministre: Li Qiang'),
          E('🇯🇵', 'Japó', 'Sanae Takaichi', 'Primera ministra, la primera dona · emperador: Naruhito'),
          E('🇮🇳', 'Índia', 'Narendra Modi', 'Primer ministre · presidenta: Droupadi Murmu'),
          E('🇰🇷', 'Corea del Sud', 'Lee Jae-myung', 'President des de juny de 2025'),
          E('🇰🇵', 'Corea del Nord', 'Kim Jong-un', 'Líder suprem'),
          E('🇵🇰', 'Pakistan', 'Shehbaz Sharif', 'Primer ministre · president: Asif Ali Zardari'),
          E('🇮🇩', 'Indonèsia', 'Prabowo Subianto', 'President'),
          E('🇵🇭', 'Filipines', 'Ferdinand Marcos Jr.', 'President'),
          E('🇻🇳', 'Vietnam', 'Tô Lâm', "Secretari general del Partit i, des d'abril de 2026, també president"),
          E('🇹🇭', 'Tailàndia', 'Anutin Charnvirakul', 'Primer ministre, reelegit el març de 2026'),
          E('🇧🇩', 'Bangladesh', 'Tarique Rahman', 'Primer ministre'),
          E('🇰🇿', 'Kazakhstan', 'Kassym-Jomart Tokàiev', 'President'),
          E('🇦🇺', 'Austràlia', 'Anthony Albanese', 'Primer ministre'),
          E('🇳🇿', 'Nova Zelanda', 'Christopher Luxon', 'Primer ministre'),
        ],
      },
      {
        title: 'Orient Mitjà',
        icon: '🕌',
        compact: true,
        entries: [
          E('🇮🇱', 'Israel', 'Benjamin Netanyahu', 'Primer ministre · president: Isaac Herzog'),
          E('🇵🇸', 'Palestina (ANP)', 'Mohammad Mustafa', "Primer ministre de l'Autoritat Nacional Palestina"),
          E('🇮🇷', 'Iran', 'Mojtaba Khamenei', "Líder suprem des de març de 2026, després que el seu pare, Ali Khamenei, morís en un atac el 28 de febrer · president: Masoud Pezeshkian"),
          E('🇮🇶', 'Iraq', 'Ali al-Zaidi', "Primer ministre des de maig de 2026, el més jove de la història del país · president: Nizar Amidi"),
          E('🇸🇾', 'Síria', 'Ahmed al-Sharaa', "President des de gener de 2025, després de la caiguda d'Assad"),
          E('🇱🇧', 'Líban', 'Joseph Aoun', 'President · primer ministre: Nawaf Salam'),
          E('🇸🇦', 'Aràbia Saudita', 'Salman bin Abdulaziz', 'Rei · príncep hereu i primer ministre: Mohammed bin Salman'),
          E('🇦🇪', 'Emirats Àrabs Units', 'Mohamed bin Zayed', 'President'),
          E('🇶🇦', 'Qatar', 'Tamim bin Hamad Al Thani', 'Emir'),
          E('🇯🇴', 'Jordània', 'Abdullah II', 'Rei · primer ministre: Jafar Hassan'),
          E('🇪🇬', 'Egipte', 'Abdel Fattah al-Sisi', 'President · primer ministre: Mostafa Madbouly'),
        ],
      },
      {
        title: 'Àfrica',
        icon: '🌍',
        compact: true,
        entries: [
          E('🇲🇦', 'Marroc', 'Mohammed VI', 'Rei · primer ministre: Aziz Akhannouch · eleccions legislatives el 23 de setembre de 2026', true),
          E('🇩🇿', 'Algèria', 'Abdelmadjid Tebboune', 'President · primer ministre: Sifi Ghrieb'),
          E('🇹🇳', 'Tunísia', 'Kaïs Saïed', 'President · primera ministra: Sara Zaafarani'),
          E('🇿🇦', 'Sud-àfrica', 'Cyril Ramaphosa', 'President'),
          E('🇳🇬', 'Nigèria', 'Bola Tinubu', 'President'),
          E('🇪🇹', 'Etiòpia', 'Abiy Ahmed', 'Primer ministre'),
          E('🇰🇪', 'Kenya', 'William Ruto', 'President'),
          E('🇸🇳', 'Senegal', 'Bassirou Diomaye Faye', "President · primer ministre: Ahmadou Al Aminou Lo, des de maig de 2026; Ousmane Sonko, destituït, presideix ara l'Assemblea"),
          E('🇬🇭', 'Ghana', 'John Mahama', 'President'),
          E('🇦🇴', 'Angola', 'João Lourenço', 'President'),
          E('🇲🇿', 'Moçambic', 'Daniel Chapo', 'President'),
          E('🇬🇶', 'Guinea Equatorial', 'Teodoro Obiang', 'President'),
        ],
      },
    ],
  },
  {
    id: 'religio',
    title: 'Vaticà i religió',
    shortLabel: 'Religió',
    icon: '✝️',
    accent: 'from-yellow-400 to-amber-600',
    subsections: [
      {
        title: 'Església catòlica',
        icon: '✝️',
        entries: [
          E('🇻🇦', 'Papa', 'Lleó XIV', "Robert Francis Prevost · elegit el 8 de maig de 2025; primer papa nascut als Estats Units. Succeeix Francesc, mort el 21 d'abril de 2025"),
          E('🇻🇦', "Cardenal secretari d'Estat", 'Pietro Parolin'),
          E('🇻🇦', 'Presidenta del Governatorat de la Ciutat del Vaticà', 'Raffaella Petrini', 'Primera dona al càrrec'),
          E('⛪', 'President de la Conferència Episcopal Espanyola', 'Luis Argüello'),
          E('🇦🇩', "Bisbe d'Urgell i copríncep d'Andorra", 'Josep-Lluís Serrano Pentinat'),
        ],
      },
    ],
  },
  {
    id: 'fets-clau',
    title: 'Fets clau 2025-2026',
    shortLabel: 'Fets clau',
    icon: '📰',
    accent: 'from-slate-500 to-slate-700',
    subsections: [
      {
        title: 'Món',
        icon: '🌍',
        entries: [
          E('🇻🇪', '3 de gener de 2026', 'Els EUA capturen Nicolás Maduro', 'Delcy Rodríguez passa a ser presidenta encarregada de Veneçuela'),
          E('🇮🇷', '28 de febrer de 2026', 'Mor Ali Khamenei en un atac', "El seu fill Mojtaba el succeeix com a líder suprem de l'Iran en plena guerra amb els EUA i Israel"),
          E('🇭🇺', '12 d\'abril de 2026', 'Orbán perd les eleccions a Hongria', 'El partit Tisza de Péter Magyar guanya amb majoria de dos terços'),
          E('🇬🇧', '20 de juliol de 2026', 'Andy Burnham, primer ministre britànic', 'Substitueix Keir Starmer al capdavant del Govern'),
          E('🇳🇴', "28 d'agost de 2026", 'Mor el rei Harald V de Noruega', 'El succeeix el seu fill, Haakon VIII'),
          E('🇺🇳', 'Setembre de 2026', 'Cursa per succeir Guterres a l\'ONU', 'El nou secretari general començarà el gener de 2027'),
        ],
      },
      {
        title: 'Espanya i Catalunya',
        icon: '🇪🇸',
        entries: [
          E('🟠', 'Octubre de 2025', 'Junts trenca amb el PSOE', "Carles Puigdemont escenifica la ruptura de l'acord d'investidura des de Perpinyà"),
          E('🌧️', '3 de novembre de 2025', 'Dimiteix Carlos Mazón', "Per la gestió de la DANA del 29 d'octubre de 2024, que va causar 229 morts al País Valencià"),
          E('⚖️', 'Novembre de 2025', "Dimiteix el fiscal general de l'Estat", 'Álvaro García Ortiz, condemnat pel Tribunal Suprem per revelació de secrets; el substitueix Teresa Peramato'),
          E('🏦', 'Octubre de 2025', "Fracassa l'OPA del BBVA sobre el Sabadell", "L'oferta hostil no arriba al mínim d'acceptació"),
          E('🎤', 'Maig de 2026', 'Espanya no va a Eurovisió', "Boicot de RTVE per la participació d'Israel"),
          E('👮', '15 de setembre de 2026', 'Sílvia Catà, primera comissària en cap dels Mossos', 'Substitueix Miquel Esquius', true),
        ],
      },
    ],
  },
];

/* ═══════════════════════════════ PREMIS ═══════════════════════════════ */

export const PREMIS = [
  {
    id: 'nobel-2025',
    title: 'Premis Nobel 2025',
    shortLabel: 'Nobel',
    icon: '🥇',
    accent: 'from-amber-400 to-yellow-600',
    subsections: [
      {
        title: 'Els sis Nobel de 2025 (els de 2026 s\'anuncien a l\'octubre)',
        icon: '🥇',
        entries: [
          E('🇻🇪', 'Nobel de la Pau', 'María Corina Machado', 'Líder opositora veneçolana, per la lluita pels drets democràtics a Veneçuela'),
          E('🇭🇺', 'Nobel de Literatura', 'László Krasznahorkai', 'Escriptor hongarès'),
          E('🔬', 'Nobel de Medicina', 'Mary E. Brunkow, Fred Ramsdell i Shimon Sakaguchi', 'Per la tolerància immunitària perifèrica (cèl·lules T reguladores)'),
          E('⚛️', 'Nobel de Física', 'John Clarke, Michel H. Devoret i John M. Martinis', "Per l'efecte túnel quàntic macroscòpic en circuits elèctrics"),
          E('🧪', 'Nobel de Química', 'Susumu Kitagawa, Richard Robson i Omar M. Yaghi', 'Per les estructures metal·lorgàniques (MOF)'),
          E('💶', "Nobel d'Economia", 'Joel Mokyr, Philippe Aghion i Peter Howitt', 'Per explicar el creixement econòmic impulsat per la innovació'),
        ],
      },
    ],
  },
  {
    id: 'princesa-asturies',
    title: "Premis Princesa d'Astúries",
    shortLabel: "Princesa d'Astúries",
    icon: '👑',
    accent: 'from-blue-500 to-indigo-700',
    subsections: [
      {
        title: "Edició 2026 · lliurament a Oviedo el 23 d'octubre",
        icon: '👑',
        entries: [
          E('🇬🇧', 'Lletres', 'Julian Barnes', 'Escriptor britànic'),
          E('🇺🇸', 'Arts', 'Patti Smith', 'Cantant, poeta i escriptora'),
          E('🇯🇵', 'Comunicació i Humanitats', 'Studio Ghibli', "Estudi d'animació japonès"),
          E('🇬🇧', 'Ciències Socials', 'Timothy Garton Ash', 'Historiador britànic'),
          E('🔬', 'Investigació Científica i Tècnica', 'David Klenerman, Shankar Balasubramanian i Pascal Mayer', "Per la seqüenciació de nova generació de l'ADN"),
          E('🇳🇴', 'Cooperació Internacional', 'Reserva Mundial de Llavors de Svalbard'),
          E('🇦🇷', 'Esports', 'Leo Messi'),
          E('🚀', 'Concòrdia', 'Christina Koch', 'Astronauta de la NASA (missió Artemis II)'),
        ],
      },
      {
        title: 'Edició 2025',
        icon: '📜',
        compact: true,
        entries: [
          E('🇪🇸', 'Lletres', 'Eduardo Mendoza'),
          E('🇲🇽', 'Arts', 'Graciela Iturbide', 'Fotògrafa'),
          E('🇩🇪', 'Comunicació i Humanitats', 'Byung-Chul Han', 'Filòsof'),
          E('🇺🇸', 'Ciències Socials', 'Douglas Massey'),
          E('🧬', 'Investigació Científica i Tècnica', 'Mary-Claire King'),
          E('🇮🇹', 'Cooperació Internacional', 'Mario Draghi'),
          E('🇺🇸', 'Esports', 'Serena Williams'),
          E('🇲🇽', 'Concòrdia', "Museu Nacional d'Antropologia de Mèxic"),
        ],
      },
    ],
  },
  {
    id: 'cinema',
    title: 'Cinema',
    shortLabel: 'Cinema',
    icon: '🎬',
    accent: 'from-rose-500 to-red-700',
    subsections: [
      {
        title: 'Oscars 2026 (98a edició, 15 de març)',
        icon: '🏆',
        entries: [
          E('🎬', 'Millor pel·lícula', 'One Battle After Another', 'La gran guanyadora, amb sis Oscars'),
          E('🎬', 'Millor direcció', 'Paul Thomas Anderson', 'One Battle After Another'),
          E('🎬', 'Millor actor', 'Michael B. Jordan', 'Sinners'),
          E('🎬', 'Millor actriu', 'Jessie Buckley', 'Hamnet'),
          E('🎬', 'Millor actor secundari', 'Sean Penn', 'One Battle After Another'),
          E('🎬', 'Millor actriu secundària', 'Amy Madigan', 'Weapons'),
          E('🇳🇴', 'Millor pel·lícula internacional', 'Sentimental Value', 'Noruega'),
          E('🎬', "Millor pel·lícula d'animació", 'KPop Demon Hunters'),
        ],
      },
      {
        title: 'Goya 2026 (40a edició)',
        icon: '🇪🇸',
        entries: [
          E('🎬', 'Millor pel·lícula', 'Los domingos', "D'Alauda Ruiz de Azúa; també guió original i actriu"),
          E('🎬', 'Millor direcció', 'Alauda Ruiz de Azúa', 'Los domingos'),
          E('🎬', 'Millor actor protagonista', 'José Ramón Soroiz', 'Maspalomas'),
          E('🎬', 'Millor actriu protagonista', 'Patricia López Arnaiz', 'Los domingos'),
          E('🎬', 'Millor direcció novella', 'Eva Libertad', 'Sorda'),
          E('🎬', 'Millor actor secundari', 'Álvaro Cervantes', 'Sorda'),
          E('🎬', 'Millor actriu revelació', 'Miriam Garlo', 'Sorda'),
        ],
      },
      {
        title: 'Premis Gaudí 2026',
        icon: '🎞️',
        entries: [
          E('🎬', 'Millor pel·lícula', 'Frontera', 'De Judith Colell'),
          E('🎬', 'Millor pel·lícula en llengua no catalana', 'Sorda'),
          E('🎬', 'Més premiada', 'Sirât', "D'Oliver Laxe, amb vuit premis"),
        ],
      },
      {
        title: 'Festivals i altres premis',
        icon: '🌟',
        entries: [
          E('🇷🇴', "Palma d'Or de Canes 2026", 'Fjord', 'De Cristian Mungiu, la seva segona Palma'),
          E('🇪🇸', 'Millor direcció a Canes 2026 (ex aequo)', 'Javier Ambrossi i Javier Calvo (Los Javis)', 'Per La bola negra; comparteixen el premi amb Pawel Pawlikowski'),
          E('🇷🇺', 'Gran Premi de Canes 2026', 'Minotaure', "D'Andrei Zviàguintsev"),
          E('🇩🇰', "Lleó d'Or de Venècia 2026", 'Woman Unknown', "De May el-Toukhy · millor actor: John Malkovich", true),
          E('🇩🇪', "Os d'Or de Berlín 2026", 'Yellow Letters', "D'İlker Çatak"),
          E('🇪🇸', "Conxa d'Or de Sant Sebastià 2025", 'Los domingos', "D'Alauda Ruiz de Azúa"),
          E('🇬🇧', 'Globus d\'Or 2026 · drama', 'Hamnet', 'Comèdia o musical: One Battle After Another'),
          E('🇬🇧', 'BAFTA 2026 · millor pel·lícula', 'One Battle After Another'),
        ],
      },
    ],
  },
  {
    id: 'lletres',
    title: 'Lletres',
    shortLabel: 'Lletres',
    icon: '📚',
    accent: 'from-emerald-500 to-teal-700',
    subsections: [
      {
        title: 'En català',
        icon: '📗',
        entries: [
          E('📖', "Premi d'Honor de les Lletres Catalanes 2026", 'Biel Mesquida', "58a edició, atorgat per Òmnium Cultural"),
          E('📖', 'Premi Sant Jordi de novel·la 2025', 'Roc Casagran', 'Somiàvem una illa'),
          E('📖', 'Premi Ramon Llull 2026', 'Agnès Marquès', 'La segona vida de Ginebra Vern'),
        ],
      },
      {
        title: 'En castellà',
        icon: '📘',
        entries: [
          E('🇲🇽', 'Premi Cervantes 2025', 'Gonzalo Celorio', "Escriptor mexicà; el va rebre dels Reis el 23 d'abril de 2026 a Alcalá de Henares · 125.000 €"),
          E('🇪🇸', 'Premi Nacional de les Lletres Espanyoles 2025', 'María Victoria Atencia', 'Poeta malaguenya'),
          E('🇪🇸', 'Premi Nacional de Narrativa 2025', 'Paco Cerdà', 'Presentes'),
          E('📖', 'Premi Planeta 2025', 'Juan del Val', 'Vera, una historia de amor · finalista: Ángela Banzas · 1.000.000 €'),
          E('📖', 'Premi Nadal 2026', 'David Uclés', 'La ciudad de las luces muertas'),
          E('🇲🇽', 'Premi Alfaguara 2026', 'David Toscana', 'El ejército ciego'),
        ],
      },
      {
        title: 'Internacionals',
        icon: '🌍',
        entries: [
          E('🇬🇧', 'Premi Booker 2025', 'David Szalay', 'Flesh'),
          E('🇫🇷', 'Premi Goncourt 2025', 'Laurent Mauvignier', 'La maison vide'),
          E('🇺🇸', 'Premi Pulitzer de ficció 2026', 'Daniel Kraus', 'Angel Down'),
        ],
      },
    ],
  },
  {
    id: 'musica',
    title: 'Música',
    shortLabel: 'Música',
    icon: '🎵',
    accent: 'from-fuchsia-500 to-purple-700',
    subsections: [
      {
        title: 'Grammy 2026 (68a edició)',
        icon: '🎤',
        entries: [
          E('🇵🇷', "Àlbum de l'any", 'Bad Bunny', "DeBÍ TiRAR MáS FOToS · el primer àlbum majoritàriament en castellà que ho guanya"),
          E('🇺🇸', "Enregistrament de l'any", 'Kendrick Lamar i SZA', 'luther'),
          E('🇺🇸', "Cançó de l'any", 'Billie Eilish', 'Wildflower'),
          E('🇬🇧', 'Millor artista revelació', 'Olivia Dean'),
        ],
      },
      {
        title: 'Grammy Llatins 2025',
        icon: '🎸',
        entries: [
          E('🇵🇷', "Àlbum de l'any", 'Bad Bunny', 'DeBÍ TiRAR MáS FOToS'),
          E('🇪🇸', "Enregistrament de l'any", 'Alejandro Sanz', 'Palmeras en el jardín'),
          E('🇨🇴', "Cançó de l'any", 'Karol G', 'Si antes te hubiera conocido'),
          E('🎶', 'Millor artista revelació', 'Paloma Morphy'),
        ],
      },
      {
        title: 'Eurovisió',
        icon: '🎙️',
        entries: [
          E('🇧🇬', 'Eurovisió 2026 (Viena)', 'Bulgària', 'Dara, amb «Bangaranga» · 516 punts; primera victòria del país'),
          E('🇪🇸', 'Espanya a Eurovisió 2026', 'No hi va participar', "Boicot per la participació d'Israel"),
          E('🇪🇸', 'Benidorm Fest 2026', 'Tony Grox i Lucycalys', "Primer guanyador que no va representar Espanya, pel boicot"),
        ],
      },
    ],
  },
  {
    id: 'ciencia-societat',
    title: 'Ciència, arquitectura i societat',
    shortLabel: 'Ciència i societat',
    icon: '🔭',
    accent: 'from-cyan-500 to-blue-700',
    subsections: [
      {
        title: 'Ciència i arquitectura',
        icon: '🔭',
        entries: [
          E('🇨🇱', 'Premi Pritzker 2026 (arquitectura)', 'Smiljan Radić', 'Arquitecte xilè'),
          E('🇩🇪', 'Premi Abel 2026 (matemàtiques)', 'Gerd Faltings', 'Primer alemany que el guanya'),
          E('📐', 'Medalla Fields 2026', 'Yu Deng, John Pardon, Jacob Tsimerman i Hong Wang', 'Per primera vegada, dos matemàtics xinesos en la mateixa edició'),
        ],
      },
      {
        title: 'Societat i drets',
        icon: '🕊️',
        entries: [
          E('🇪🇺', 'Premi Sàkharov 2025', 'Andrzej Poczobut i Mzia Amaglobeli', 'Periodistes empresonats a Bielorússia i Geòrgia'),
          E('🇮🇹', 'Premi Carlemany 2026', 'Mario Draghi'),
          E('🤖', "Persona de l'Any 2025 de la revista Time", "Els arquitectes de la intel·ligència artificial", 'Entre d\'altres, Jensen Huang, Sam Altman, Mark Zuckerberg i Elon Musk'),
          E('🟥', 'Creus de Sant Jordi 2026', 'Sílvia Munt, Enric Majó, Júlia Otero, Fermí Puig, Victòria Camps, Maite Carranza i Joan Fontcuberta, entre d\'altres', 'També la Universitat de Barcelona, entre les entitats'),
        ],
      },
    ],
  },
  {
    id: 'premis-esportius',
    title: 'Premis esportius',
    shortLabel: 'Premis esportius',
    icon: '🏅',
    accent: 'from-yellow-500 to-orange-600',
    subsections: [
      {
        title: 'Futbol',
        icon: '⚽',
        entries: [
          E('🇫🇷', "Pilota d'Or 2025", 'Ousmane Dembélé', 'PSG · la primera de la seva carrera'),
          E('🇪🇸', "Pilota d'Or femenina 2025", 'Aitana Bonmatí', 'Barça · la tercera seguida'),
          E('🇪🇸', 'Trofeu Kopa 2025 (millor jove)', 'Lamine Yamal', 'El segon; en femení, Vicky López'),
          E('🇫🇷', 'The Best FIFA 2025', 'Ousmane Dembélé i Aitana Bonmatí', 'Millors entrenadors: Luis Enrique i Sarina Wiegman'),
          E('🇫🇷', 'Golden Boy 2025', 'Désiré Doué', 'PSG'),
        ],
      },
      {
        title: 'Laureus 2026 (Madrid)',
        icon: '🏅',
        entries: [
          E('🇪🇸', 'Esportista masculí', 'Carlos Alcaraz'),
          E('🇧🇾', 'Esportista femenina', 'Aryna Sabalenka'),
          E('🇪🇸', 'Esportista revelació jove', 'Lamine Yamal'),
          E('🇩🇪', 'Premi a la inspiració', 'Toni Kroos'),
          E('🇫🇷', 'Equip', 'Paris Saint-Germain'),
          E('🇬🇧', 'Revelació', 'Lando Norris'),
        ],
      },
    ],
  },
];

/* ═══════════════════════════════ ESPORTS ═══════════════════════════════ */

export const ESPORTS = [
  {
    id: 'futbol-seleccions',
    title: 'Futbol: seleccions',
    shortLabel: 'Seleccions',
    icon: '🌍',
    accent: 'from-red-500 to-yellow-500',
    subsections: [
      {
        title: 'Mundial 2026 (EUA, Mèxic i Canadà)',
        icon: '🏆',
        entries: [
          E('🇪🇸', 'Campiona del món', 'Espanya', "1-0 a l'Argentina a la pròrroga, el 19 de juliol a Nova York-Nova Jersey · gol de Ferran Torres al minut 106 · segon Mundial després del de 2010", true),
          E('🇪🇸', 'Seleccionador', 'Luis de la Fuente'),
          E('🇪🇸', "Pilota d'Or del torneig", 'Rodri', "Plata: Leo Messi · bronze: Kylian Mbappé"),
          E('🇫🇷', "Bota d'Or (màxim golejador)", 'Kylian Mbappé', "10 gols · l'únic jugador que l'ha guanyada dues vegades"),
          E('🇪🇸', "Guant d'Or (millor porter)", 'Unai Simón', 'Espanya només va encaixar un gol en set partits'),
          E('🇪🇸', 'Millor jugador jove', 'Pau Cubarsí'),
          E('🌍', 'Novetats del torneig', '48 seleccions i tres països organitzadors', 'El primer Mundial amb aquest format'),
        ],
      },
      {
        title: 'Altres competicions',
        icon: '🥇',
        entries: [
          E('🏴', 'Eurocopa femenina 2025', 'Anglaterra', "Guanya Espanya als penals (3-1) després de l'1-1, a Basilea · Espanya, subcampiona"),
          E('🇵🇹', 'Lliga de Nacions 2025', 'Portugal', 'Guanya Espanya a la final als penals'),
        ],
      },
    ],
  },
  {
    id: 'futbol-clubs',
    title: 'Futbol: clubs',
    shortLabel: 'Clubs',
    icon: '⚽',
    accent: 'from-blue-600 to-indigo-800',
    subsections: [
      {
        title: 'Competicions europees i mundials 2025-26',
        icon: '🏆',
        entries: [
          E('🇫🇷', 'Champions League', 'Paris Saint-Germain', "1-1 contra l'Arsenal i 4-3 als penals, a Budapest el 30 de maig · revalida el títol"),
          E('🏴', 'Europa League', 'Aston Villa', '3-0 al Friburg a Istanbul · el seu primer títol en aquesta competició'),
          E('🏴', 'Conference League', 'Crystal Palace', '1-0 al Rayo Vallecano a Leipzig'),
          E('🇫🇷', "Supercopa d'Europa 2026", 'Paris Saint-Germain', "2-1 a l'Aston Villa a Salzburg, el 12 d'agost", true),
          E('🇫🇷', 'Copa Intercontinental 2025', 'Paris Saint-Germain', 'Guanya el Flamengo als penals després de l\'1-1'),
          E('🏴', 'Mundial de Clubs 2025', 'Chelsea', '3-0 al PSG a la final'),
          E('🇪🇸', 'Champions femenina', 'FC Barcelona', "4-0 a l'OL Lyonnes a Oslo · el seu quart títol"),
        ],
      },
      {
        title: 'Lligues i copes 2025-26',
        icon: '🇪🇸',
        entries: [
          E('🇪🇸', 'LaLiga', 'FC Barcelona', 'Segona lliga seguida'),
          E('🇪🇸', 'Copa del Rei', 'Reial Societat', "2-2 amb l'Atlètic de Madrid i 4-3 als penals, a La Cartuja el 18 d'abril · la seva quarta Copa"),
          E('🇪🇸', "Supercopa d'Espanya 2026", 'FC Barcelona', '3-2 al Reial Madrid a Jiddah · la seva 16a Supercopa'),
          E('🇪🇸', 'Liga F', 'FC Barcelona', 'Setena seguida'),
          E('🏴', 'Premier League', 'Arsenal', 'La primera en 22 anys'),
          E('🇮🇹', 'Serie A', 'Inter de Milà', 'El seu 21è scudetto'),
          E('🇩🇪', 'Bundesliga', 'Bayern de Munic'),
          E('🇫🇷', 'Ligue 1', 'Paris Saint-Germain', 'Cinquena seguida'),
        ],
      },
      {
        title: 'Dirigents',
        icon: '👔',
        entries: [
          E('🇪🇸', 'President del FC Barcelona', 'Joan Laporta', 'Reelegit el 15 de març de 2026 amb el 68 % dels vots, davant de Víctor Font'),
          E('🇪🇸', 'President del Reial Madrid', 'Florentino Pérez'),
          E('🇪🇸', 'President de la RFEF', 'Rafael Louzán'),
          E('🇪🇸', 'President de LaLiga', 'Javier Tebas'),
          E('🌍', 'President de la FIFA', 'Gianni Infantino'),
          E('🇪🇺', 'President de la UEFA', 'Aleksander Čeferin'),
          E('🇪🇸', 'President del Comitè Olímpic Espanyol', 'Alejandro Blanco'),
        ],
      },
    ],
  },
  {
    id: 'tennis',
    title: 'Tennis',
    shortLabel: 'Tennis',
    icon: '🎾',
    accent: 'from-lime-500 to-green-700',
    subsections: [
      {
        title: 'Grand Slams 2026',
        icon: '🏆',
        entries: [
          E('🇪🇸', "Open d'Austràlia · masculí", 'Carlos Alcaraz', 'Guanya Novak Djokovic (2-6, 6-2, 6-3, 7-5) i completa el Grand Slam de carrera'),
          E('🇰🇿', "Open d'Austràlia · femení", 'Elena Rybakina', 'Guanya Aryna Sabalenka (6-4, 4-6, 6-4)'),
          E('🇩🇪', 'Roland Garros · masculí', 'Alexander Zverev', 'Guanya Flavio Cobolli (7-6, 6-4, 6-3) · el seu primer Grand Slam'),
          E('🇷🇺', 'Roland Garros · femení', 'Mirra Andreeva', 'Guanya Maja Chwalińska (6-3, 6-2) · primer Grand Slam, amb 19 anys'),
          E('🇮🇹', 'Wimbledon · masculí', 'Jannik Sinner', 'Guanya Zverev (6-7, 7-6, 6-3, 6-4) · segon Wimbledon seguit'),
          E('🇨🇿', 'Wimbledon · femení', 'Linda Nosková', 'Guanya Karolína Muchová en una final txeca'),
          E('🇩🇪', 'US Open · masculí', 'Alexander Zverev', 'Guanya Ben Shelton (6-3, 7-6, 5-7, 6-2) el 13 de setembre · el seu segon Grand Slam de l\'any', true),
          E('🇰🇿', 'US Open · femení', 'Elena Rybakina', 'Guanya Sabalenka (6-4, 5-7, 6-2)', true),
        ],
      },
      {
        title: 'Altres',
        icon: '🎾',
        entries: [
          E('🇮🇹', 'Copa Davis 2025', 'Itàlia', 'Guanya Espanya a la final · tercera seguida'),
          E('🇮🇹', 'ATP Finals 2025', 'Jannik Sinner', 'Guanya Alcaraz a la final'),
          E('🇰🇿', 'WTA Finals 2025', 'Elena Rybakina', 'Guanya Sabalenka a la final'),
          E('🇮🇹', 'Número 1 del rànquing ATP', 'Jannik Sinner', 'A 14 de setembre de 2026'),
        ],
      },
    ],
  },
  {
    id: 'basquet',
    title: 'Bàsquet',
    shortLabel: 'Bàsquet',
    icon: '🏀',
    accent: 'from-orange-500 to-amber-700',
    subsections: [
      {
        title: 'Temporada 2025-26',
        icon: '🏀',
        entries: [
          E('🇺🇸', 'NBA', 'New York Knicks', 'Guanyen els San Antonio Spurs (4-1) · primer títol des de 1973 · MVP de les finals: Jalen Brunson'),
          E('🇨🇦', 'MVP de la temporada NBA', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder · el segon seguit'),
          E('🇬🇷', 'Eurolliga', 'Olympiacos', 'Guanya el Reial Madrid (92-85) a Atenes · MVP: Evan Fournier'),
          E('🇪🇸', 'Lliga Endesa (ACB)', 'València Basket', 'Guanya el Barça a la final · segona lliga del club'),
          E('🇪🇸', 'Copa del Rei', 'Baskonia', 'Guanya el Reial Madrid a la final · setena Copa'),
          E('🇺🇸', 'Mundial femení 2026', 'Estats Units', '97-79 a França a la final · cinquè títol seguit', true),
          E('🇺🇸', 'WNBA 2025', 'Las Vegas Aces', 'Escombren els Phoenix Mercury (4-0)'),
        ],
      },
    ],
  },
  {
    id: 'motor',
    title: 'Motor',
    shortLabel: 'Motor',
    icon: '🏎️',
    accent: 'from-red-600 to-rose-800',
    subsections: [
      {
        title: 'Fórmula 1',
        icon: '🏎️',
        entries: [
          E('🇬🇧', 'Campió del món 2025', 'Lando Norris', 'McLaren · el seu primer títol; Verstappen a dos punts i Piastri tercer'),
          E('🇮🇹', 'Líder del Mundial 2026', 'Kimi Antonelli', "Mercedes · 292 punts i vuit victòries després del GP d'Espanya a Madrid; 2n George Russell, 3r Lewis Hamilton", true),
        ],
      },
      {
        title: 'Motociclisme',
        icon: '🏍️',
        entries: [
          E('🇪🇸', 'Campió de MotoGP 2025', 'Marc Márquez', 'Ducati · setè títol a la categoria reina'),
          E('🇪🇸', 'Líder de MotoGP 2026', 'Marc Márquez', 'Passa al capdavant després del doble triomf a Misano, empatat a punts amb Jorge Martín', true),
        ],
      },
      {
        title: 'Dakar 2026',
        icon: '🏜️',
        entries: [
          E('🇶🇦', 'Cotxes', 'Nasser Al-Attiyah', 'Dacia · el seu sisè Dakar · 2n Nani Roma; Carlos Sainz, 5è'),
          E('🇦🇷', 'Motos', 'Luciano Benavides', 'KTM · guanya per només 2 segons Ricky Brabec, el final més ajustat de la història'),
        ],
      },
    ],
  },
  {
    id: 'ciclisme',
    title: 'Ciclisme',
    shortLabel: 'Ciclisme',
    icon: '🚴',
    accent: 'from-yellow-400 to-pink-600',
    subsections: [
      {
        title: 'Grans Voltes 2026',
        icon: '🚴',
        entries: [
          E('🇸🇮', 'Tour de França', 'Tadej Pogačar', "El seu cinquè Tour: iguala Anquetil, Merckx, Hinault i Indurain · 2n Remco Evenepoel, 3r Isaac del Toro · va sortir de Barcelona"),
          E('🇩🇰', "Giro d'Itàlia", 'Jonas Vingegaard', 'Completa les tres Grans Voltes · 2n Felix Gall, 3r Jai Hindley'),
          E('🇪🇸', 'Vuelta a Espanya', 'Enric Mas', "Movistar · primer guanyador espanyol des de Contador el 2014 · 2n Primož Roglič, 3r Felix Gall · final a l'Alhambra de Granada", true),
        ],
      },
      {
        title: '2025',
        icon: '📅',
        entries: [
          E('🇸🇮', 'Tour de França 2025', 'Tadej Pogačar', '2n Jonas Vingegaard'),
          E('🇩🇰', 'Vuelta a Espanya 2025', 'Jonas Vingegaard', '2n João Almeida'),
          E('🇸🇮', 'Mundial en ruta 2025 (Kigali)', 'Tadej Pogačar', 'El segon seguit'),
        ],
      },
    ],
  },
  {
    id: 'altres-esports',
    title: 'Altres esports',
    shortLabel: 'Altres',
    icon: '🏅',
    accent: 'from-teal-500 to-emerald-700',
    subsections: [
      {
        title: "Jocs Olímpics d'Hivern de Milà-Cortina 2026",
        icon: '⛷️',
        entries: [
          E('🇪🇸', 'Balanç espanyol', '1 or i 2 bronzes', "El millor resultat de la història d'Espanya en uns Jocs d'hivern"),
          E('🇪🇸', 'Or en esquí de muntanya (esprint)', 'Oriol Cardona', "Primer or olímpic d'hivern espanyol des de Paquito Fernández Ochoa (1972)"),
          E('🇪🇸', 'Bronzes en esquí de muntanya', 'Ana Alonso', "A l'esprint i al relleu mixt, amb Cardona"),
        ],
      },
      {
        title: 'Atletisme i natació',
        icon: '🏃',
        entries: [
          E('🇪🇸', "Europeu d'atletisme 2026 (Birmingham)", 'María Pérez i Paul McGrath', "Els dos ors espanyols, tots dos en marxa; María Pérez amb rècord del món"),
          E('🇪🇸', 'Mundial de natació 2025 (Singapur)', 'Iris Tió', 'Tres ors en natació artística'),
          E('🇪🇸', 'Europeu de natació 2026 (París)', 'Iris Tió', 'Or en solo tècnic · Hugo González, plata en 200 estils'),
        ],
      },
      {
        title: 'Handbol',
        icon: '🤾',
        entries: [
          E('🇩🇰', 'Europeu masculí 2026', 'Dinamarca', '34-27 a Alemanya a la final'),
          E('🇳🇴', 'Mundial femení 2025', 'Noruega', 'Alemanya, subcampiona'),
          E('🇪🇸', 'Champions League 2026', 'FC Barcelona', '37-34 al Füchse Berlin a Colònia · el seu 12è títol'),
        ],
      },
      {
        title: 'Golf, rugbi i futbol americà',
        icon: '⛳',
        entries: [
          E('🇬🇧', 'Masters 2026', 'Rory McIlroy'),
          E('🇬🇧', 'PGA Championship 2026', 'Aaron Rai', 'El seu primer major'),
          E('🇺🇸', 'US Open de golf 2026', 'Wyndham Clark', 'El seu segon US Open'),
          E('🇳🇿', 'The Open 2026', 'Ryan Fox', 'El seu primer major'),
          E('🇫🇷', 'Sis Nacions 2026', 'França', 'Revalida el títol'),
          E('🇺🇸', 'Super Bowl LX', 'Seattle Seahawks', '29-13 als New England Patriots · MVP: Kenneth Walker III'),
        ],
      },
    ],
  },
];
